name: CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: microsoft/setup-msbuild@v1.1
      - run: Get-Command msbuild
        shell: pwsh
      - run: Get-Command nonexistentcommand
        shell: pwsh
       
