name: CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'
      - run: Get-Command msbuild
        shell: pwsh
      - run: Get-Command nonexistentcommand
        shell: pwsh
       
